# Generated by Django 5.1.1 on 2024-09-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languge', models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'France')], default='arabic', help_text='Book Language', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.book')),
            ],
        ),
    ]
