# Generated by Django 5.1.1 on 2024-09-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_booklanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklanguage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booklanguage',
            name='languge',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.booklanguage'),
        ),
        migrations.AddField(
            model_name='booklanguage',
            name='name',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'France')], default='arabic', help_text='Book Language', max_length=2, unique=True),
        ),
    ]
