# Generated by Django 5.1.1 on 2024-09-14 19:35

import catalog.languages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_booklanguage_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auther',
            new_name='Author',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000),
        ),
        migrations.AlterField(
            model_name='booklanguage',
            name='name',
            field=models.CharField(choices=catalog.languages.book_languages, default='arabic', help_text='Book Language', max_length=5, unique=True),
        ),
    ]
